-- pack rules already applied manually

ALTER TABLE `Pack`
ADD COLUMN `type` ENUM('FREE', 'SMALL', 'MEDIUM', 'LARGE') NOT NULL DEFAULT 'SMALL',
ADD COLUMN `commonChance` DOUBLE NOT NULL DEFAULT 100,
ADD COLUMN `rareChance` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `epicChance` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `legendaryChance` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `guaranteedLegendary` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `dailyLimit` BOOLEAN NOT NULL DEFAULT false;